articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('create/', views.create_post, name='create'),
    path('category/<str:category>/', views.article_category, name='category'),
    path('detail/<int:pk>/', views.article_detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from articles.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('articles/', include('articles.urls'))
]

articles/models.py
from django.db import models
from django.shortcuts import reverse


class Article(models.Model):
    title = models.CharField(max_length=255)
    category = models.CharField(max_length=100)
    short_content = models.TextField()
    long_content = models.TextField()
    author = models.CharField(max_length=255)
    created_date = models.DateField(auto_now_add=True)

    def get_detail_url(self):
        return reverse('articles:detail', args=[self.pk])

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotAllowed
from .models import Article


def home(request):
    articles = Article.objects.all()
    ctx = {'articles': articles}
    return render(request, 'index.html', ctx)

def create_post(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        category = request.POST.get('category')
        short_content = request.POST.get('short_content')
        long_content = request.POST.get('long_content')
        author = request.POST.get('author')
        if title and category and short_content and long_content and author:
            Article.objects.create(
                title=title,
                category=category,
                short_content=short_content,
                long_content=long_content,
                author=author,
            )
            return redirect('home')
    return render(request, 'articles/add-post.html')

def article_category(request, category):
    articles = Article.objects.filter(category=category)
    ctx = {
        'articles': articles,
        'category': category,
    }
    return render(request, 'articles/articles-by-category.html', ctx)

def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    ctx = {'article': article}
    return render(request, 'articles/detail.html', ctx )

templates/articles/add-post.html
{% extends 'base.html' %}

{% block title %} Add New Article - Astrum IT Academy H4ck3rs {% endblock %}
{% block content %}
    <main>
        <h2>Add New Article</h2>
        <form class="article-form"  method="post">
            {% csrf_token %}
            <div>
                <label for="title">Title:</label>
                <input type="text" id="title" name="title" required>
            </div>
            <div>
                <label for="category">Category:</label>
                <select id="category" name="category" required>
                    <option value="">Select a category</option>
                    <option value="exploits">Exploits</option>
                    <option value="tools">Tools</option>
                    <option value="ctf">CTF</option>
                    <option value="tutorials">Tutorials</option>
                    <option value="news">News</option>
                </select>
            </div>
            <div>
                <label for="short_content">Short Content:</label>
                <textarea id="short_content" name="short_content" rows="3" required placeholder="Brief summary or introduction"></textarea>
            </div>
            <div>
                <label for="long_content">Long Content:</label>
                <textarea id="long_content" name="long_content" rows="10" required placeholder="Full article content"></textarea>
            </div>
            <div>
                <label for="author">Author:</label>
                <input type="text" id="author" name="author" required>
            </div>
            <div>
                <button type="submit" class="submit-button">Submit Article</button>
            </div>
        </form>
    </main>
{% endblock %}

templates/articles/articles-by-category.html
{% extends 'base.html' %}

{% block title %} Exploits Articles - Astrum IT Academy H4ck3rs {% endblock %}

{% block content %}
    <main>
        <h2>{{ category|title }} Articles</h2>
        <div class="article-list">
            {% if articles %}
                {% for article in articles %}
                    <article class="post">
                        <h3>{{ article.title }}</h3>
                        <p class="post-meta">
                            <span class="author">By: {{ article.author|default:'Unknown' }}</span>
                            <span class="date">Date:  {{ article.created_date | date:"Y-m-d" }}</span>
                        </p>
                        <p>{{ article.short_content }}</p>
                        <a href="{{ article.get_detail_url }}" class="read-more">Read More</a>
                    </article>
                {% endfor %}
            {% else %}
                <h3>Not Found!</h3>
            {% endif %}
        </div>
    </main>
{% endblock %}

templates/articles/detail.html
{% extends 'base.html' %}

{% block title %} New Zero-day Exploit Discovered in Popular CMS - Astrum IT Academy H4ck3rs {% endblock %}
{% block content %}
<main>
    <article class="post-content">
        <div class="post-meta">
            <span>Author: {{ article.author }}</span>
            <span>Date: {{ article.created_date | date:"Y-m-d" }}</span>
        </div>
            <h1>{{ article.title }}</h1>
            <p>{{ article.long_content }}</p>
    </article>
</main>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="page-container">
    <div class="content-wrap">
        {# HEAD #}
        {% include 'includes/head.html' %}

        {# NAV #}
        {% include 'includes/nav.html' %}

        {# CONTENT BLOCK #}
        {% block content %} {% endblock %}
    </div>

    {# FOOTER #}
    {% include 'includes/footer.html' %}

    <button id="mode-toggle">Light Mode</button>

    {# SCRIPTS #}
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/includes/footer.html
<footer>
    <p>&copy; 2023 Astrum IT Academy H4ck3rs. All rights reserved. Use responsibly.</p>
</footer>

templates/includes/head.html
<header>
    <h1>
        Astrum IT Academy H4ck3rs
    </h1>
</header>

templates/includes/nav.html
<nav>
    <a href="{% url 'home' %}" class="{% if request.path == '/' %}active{% endif %}">Home</a>
    <a href="{% url 'articles:category' 'exploits' %}" class="{% if 'exploits' in request.path %}active{% endif %}">Exploits</a>
    <a href="{% url 'articles:category' 'tools' %}" class="{% if 'tools' in request.path %}active{% endif %}">Tools</a>
    <a href="{% url 'articles:category' 'ctf' %}" class="{% if 'ctf' in request.path %}active{% endif %}">CTF</a>
    <a href="{% url 'articles:category' 'tutorials' %}" class="{% if 'tutorials' in request.path %}active{% endif %}">Tutorials</a>
    <a href="{% url 'articles:category' 'news' %}" class="{% if 'news' in request.path %}active{% endif %}">News</a>
    <a href="{% url 'articles:create' %}" class="{% if 'create' in request.path %}active{% endif %}">Add New Article</a>
</nav>

templates/index.html
{% extends 'base.html' %}

{% block title %} Astrum IT Academy H4ck3rs {% endblock %}
{% block content %}
<main>
    <div class="ascii-art">
 _    _            _             _        _   _
| |  | |          | |           ( )      | | | |
| |__| | __ _  ___| | _____ _ __|/ ___   | |_| | __ ___   _____ _ __
|  __  |/ _` |/ __| |/ / _ \ '__| / __|  |  _  |/ _` \ \ / / _ \ '__|
| |  | | (_| | (__|   <  __/ |    \__ \  | | | | (_| |\ V /  __/ |
|_|  |_|\__,_|\___|_|\_\___|_|    |___/  \_| |_/\__,_| \_/ \___|_|
    </div>
{% for article in articles %}
    <article class="post">
        <h2>{{ article.title }}</h2>
        <p>{{ article.short_content }}</p>
        <a href="{{ article.get_detail_url }}" class="read-more">Read More</a>
    </article>
{% empty %}
    <h2>No Found!</h2>
{% endfor %}
    </main>
{% endblock %}